# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multi_tab.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 771, 531))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_0 = QtWidgets.QWidget()
        self.tab_0.setObjectName("tab_0")
        self.frame_2 = QtWidgets.QFrame(self.tab_0)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 771, 501))
        self.frame_2.setStyleSheet("background-color: rgb(252, 175, 62);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.tab_0_input = QtWidgets.QTextEdit(self.frame_2)
        self.tab_0_input.setGeometry(QtCore.QRect(130, 30, 131, 41))
        self.tab_0_input.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.tab_0_input.setObjectName("tab_0_input")
        self.tab_0_output = QtWidgets.QTextEdit(self.frame_2)
        self.tab_0_output.setGeometry(QtCore.QRect(130, 190, 131, 71))
        self.tab_0_output.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.tab_0_output.setObjectName("tab_0_output")
        self.tab_0_button = QtWidgets.QPushButton(self.frame_2)
        self.tab_0_button.setGeometry(QtCore.QRect(150, 110, 89, 25))
        self.tab_0_button.setObjectName("tab_0_button")
        self.tabWidget.addTab(self.tab_0, "")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.frame = QtWidgets.QFrame(self.tab_1)
        self.frame.setGeometry(QtCore.QRect(0, 10, 771, 501))
        self.frame.setStyleSheet("background-color: rgb(239, 41, 41);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_file_distribution = QtWidgets.QLabel(self.frame)
        self.label_file_distribution.setGeometry(QtCore.QRect(20, 20, 101, 17))
        self.label_file_distribution.setObjectName("label_file_distribution")
        self.label_node_distribution = QtWidgets.QLabel(self.frame)
        self.label_node_distribution.setGeometry(QtCore.QRect(20, 60, 121, 17))
        self.label_node_distribution.setObjectName("label_node_distribution")
        self.input_file_distribution = QtWidgets.QTextEdit(self.frame)
        self.input_file_distribution.setGeometry(QtCore.QRect(160, 10, 161, 31))
        self.input_file_distribution.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.input_file_distribution.setObjectName("input_file_distribution")
        self.input_node_distribution = QtWidgets.QTextEdit(self.frame)
        self.input_node_distribution.setGeometry(QtCore.QRect(160, 50, 161, 31))
        self.input_node_distribution.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.input_node_distribution.setObjectName("input_node_distribution")
        self.terasort = QtWidgets.QPushButton(self.frame)
        self.terasort.setGeometry(QtCore.QRect(30, 120, 121, 25))
        self.terasort.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.terasort.setObjectName("terasort")
        self.output = QtWidgets.QTextEdit(self.frame)
        self.output.setGeometry(QtCore.QRect(30, 190, 291, 171))
        self.output.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.output.setObjectName("output")
        self.coded_terasort = QtWidgets.QPushButton(self.frame)
        self.coded_terasort.setGeometry(QtCore.QRect(200, 120, 121, 25))
        self.coded_terasort.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.coded_terasort.setObjectName("coded_terasort")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 771, 501))
        self.frame_3.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tab_0_button.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_0), _translate("MainWindow", "标签0"))
        self.label_file_distribution.setText(_translate("MainWindow", "文件分布情况："))
        self.label_node_distribution.setText(_translate("MainWindow", "节点分布情况："))
        self.terasort.setText(_translate("MainWindow", "经典以太网传输"))
        self.coded_terasort.setText(_translate("MainWindow", "网络编码传输"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "标签1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "标签2"))
